# Generated by Django 2.1.4 on 2019-01-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190107_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='users'),
        ),
        migrations.AddField(
            model_name='logger',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logger',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logger',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logger',
            name='phone_no',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Image'),
        ),
    ]
