# Generated by Django 2.1.4 on 2019-01-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190116_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Logger'),
        ),
    ]
