# Generated by Django 2.1.4 on 2019-01-17 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190116_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='/static/Images/def.jpeg', upload_to='Upload'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='accounts.Logger'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logger', to=settings.AUTH_USER_MODEL),
        ),
    ]
