# Generated by Django 2.1.4 on 2019-01-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190117_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='pp',
            field=models.CharField(default='Images/def.jpeg', max_length=255),
        ),
    ]
