# Generated by Django 2.1.4 on 2019-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190209_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orginization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginization', models.CharField(max_length=255, null=True)),
                ('first_name', models.BooleanField()),
                ('last_name', models.BooleanField()),
                ('date_of_birth', models.BooleanField()),
                ('gender', models.BooleanField()),
                ('displacement_reason', models.BooleanField()),
                ('number_of_familymembers', models.BooleanField()),
                ('disabilities', models.BooleanField()),
                ('country_of_origin', models.BooleanField()),
                ('photo', models.BooleanField()),
            ],
        ),
    ]
