# Generated by Django 2.1.4 on 2019-02-09 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_orginization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Person_Id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Registerd_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Registerd_On',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
