# Generated by Django 2.1.4 on 2019-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190209_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
