# Generated by Django 2.1.4 on 2019-02-09 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20190209_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Orginization',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='Person_Id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='Registerd_By',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='Registerd_On',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Gender'),
        ),
    ]
