# Generated by Django 2.1.4 on 2019-02-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='disabilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Disability'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_of_origin',
            field=models.CharField(max_length=50),
        ),
    ]
