# Generated by Django 2.1.4 on 2019-02-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190209_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='number_of_familymembers',
        ),
        migrations.AddField(
            model_name='family',
            name='number_of_familymembers',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
