# Generated by Django 2.1.4 on 2019-02-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190209_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='photo',
            field=models.ImageField(default='Images/def.jpeg', upload_to='Uploads/'),
        ),
    ]
